name: 'retail_analytics'
version: '1.0.0'
config-version: 2

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  euro_rate: 0.85

models:
  retail_analytics:
    # Configuration globale
    +materialized: view
    
    # Staging layer
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      
    # Intermediate layer
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]
      
      customer:
        +tags: ["intermediate", "customer"]
      
      product:
        +tags: ["intermediate", "product"]
      
      marketing:
        +tags: ["intermediate", "marketing"]
      
    # Marts layer
    marts:
      core:
        +materialized: table
        +schema: marts_core
        +tags: ["marts", "core"]
        
      customer:
        +materialized: table
        +schema: marts_customer
        +tags: ["marts", "customer"]
        
      product:
        +materialized: table
        +schema: marts_product
        +tags: ["marts", "product"]
        
      marketing:
        +materialized: table
        +schema: marts_marketing
        +tags: ["marts", "marketing"]

snapshots:
  retail_analytics:
    +target_schema: snapshots
    +strategy: check
